base_url=https://www.saucedemo.com/
browser=chrome
browser_platform=windows
browser_version=149.0.7827.201
execution_timestamp=2026-07-06T23:31:04+05:30
headless=False
implicit_wait=0
os=Windows-11-10.0.26200-SP0
pytest_exit_status=0
python_version=3.14.4 (tags/v3.14.4:23116f9, Apr  7 2026, 14:10:54) [MSC v.1944 64 bit (AMD64)]
run_id=20260706_233104
